eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-approve
  zipkin:
    base-url: http://localhost:9411
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attendance_management_system?zeroDateTimeBehavior=round&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    port: 587
    username: sjenterrement@qq.com
    password: hwiuzyqikegvgdib
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        mail:
          debug: true
mybatis:
  table:
    auto: update
  model:
    pack: com.forezp.pojo.dao
  database:
    type: mysql

mybatis-plus:
  mapper-locations: classpath*:xxxxxx/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false